// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwaQOeIMSFg2S9raaW0xwsnw9ihgYXd3s',
    appId: '1:131286891022:web:9d01fbed818084dd1eda5f',
    messagingSenderId: '131286891022',
    projectId: 'twitterzproject',
    authDomain: 'twitterzproject.firebaseapp.com',
    storageBucket: 'twitterzproject.firebasestorage.app',
    measurementId: 'G-25EEVJNVCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapzo1MvF_S4d8gXPkZpLAJ94oD3CTiHY',
    appId: '1:189891089096:android:427c5ff5fd54c4ac51cbfd',
    messagingSenderId: '189891089096',
    projectId: 'eeee-6a630',
    storageBucket: 'eeee-6a630.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzdyREQrj86SwVNDCz6hIw98ebHINxufI',
    appId: '1:131286891022:ios:1c0c1c35c4f0fda41eda5f',
    messagingSenderId: '131286891022',
    projectId: 'twitterzproject',
    storageBucket: 'twitterzproject.firebasestorage.app',
    iosBundleId: 'com.example.twitterz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzdyREQrj86SwVNDCz6hIw98ebHINxufI',
    appId: '1:131286891022:ios:1c0c1c35c4f0fda41eda5f',
    messagingSenderId: '131286891022',
    projectId: 'twitterzproject',
    storageBucket: 'twitterzproject.firebasestorage.app',
    iosBundleId: 'com.example.twitterz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwaQOeIMSFg2S9raaW0xwsnw9ihgYXd3s',
    appId: '1:131286891022:web:8145aa37b4a602c01eda5f',
    messagingSenderId: '131286891022',
    projectId: 'twitterzproject',
    authDomain: 'twitterzproject.firebaseapp.com',
    storageBucket: 'twitterzproject.firebasestorage.app',
    measurementId: 'G-VE17PHT5VH',
  );
}